config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :others
  resources :businesses

  root 'home#index'

end

app/models/business.rb
class Business < ActiveRecord::Base
	has_many :contacts
	validates :nickname, presence: true

	def self.search(query)
		if query.present?
			where(['nickname ILIKE :query OR
				other ILIKE :query OR
				corporate_name ILIKE :query', query: "%#{query}%"])
		else
			all
		end

	end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :business
	validates :business_id, presence: true

end

app/models/other.rb
class Other < ActiveRecord::Base
	belongs_to :business
	belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require 'csv'
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
    respond_to do |format|
    format.html
    format.csv do
      headers['Content-Disposition'] = "attachment; filename=\"empresas.csv\""
      headers['Content-Type'] ||= 'text/csv'
    end
    if params[:search]
      @businesses = Business.search(params[:search]).order("created_at DESC")
    else
      @businesses = Business.all.order('created_at DESC')
    end
  end
  @contact = Contact.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:corporate_name, :nickname, :segment, :cnpj, :state_registration, :address, :number, :complement, :district, :city, :cep, :uf, :country, :phone1, :phone2, :fax, :email, :url, :other)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
     respond_to do |format|
    format.html
    format.csv do
      headers['Content-Disposition'] = "attachment; filename=\"contatos.csv\""
      headers['Content-Type'] ||= 'text/csv'
    end
  end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :position, :phone, :ramal, :email, :business_id, :other)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
	end

end

app/controllers/others_controller.rb
class OthersController < ApplicationController
  before_action :set_other, only: [:show, :edit, :update, :destroy]

  # GET /others
  # GET /others.json
  def index
    @others = Other.all
  end

  # GET /others/1
  # GET /others/1.json
  def show
  end

  # GET /others/new
  def new
    @other = Other.new
  end

  # GET /others/1/edit
  def edit
  end

  # POST /others
  # POST /others.json
  def create
    @other = Other.new(other_params)

    respond_to do |format|
      if @other.save
        format.html { redirect_to @other, notice: 'Other was successfully created.' }
        format.json { render :show, status: :created, location: @other }
      else
        format.html { render :new }
        format.json { render json: @other.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /others/1
  # PATCH/PUT /others/1.json
  def update
    respond_to do |format|
      if @other.update(other_params)
        format.html { redirect_to @other, notice: 'Other was successfully updated.' }
        format.json { render :show, status: :ok, location: @other }
      else
        format.html { render :edit }
        format.json { render json: @other.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /others/1
  # DELETE /others/1.json
  def destroy
    @other.destroy
    respond_to do |format|
      format.html { redirect_to others_url, notice: 'Other was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_other
      @other = Other.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def other_params
      params.require(:other).permit(:other, :business_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/views/businesses/_search_html.erb
<%= form_tag businesses_path, method: :get, class: 'search' do %>
  <%= text_field_tag :q, @search_query%>
  <% end %>

app/views/businesses/edit.html.erb
<h1>Editando Empresa</h1>

<%= render 'form' %>

<%= link_to businesses_path, class: "btn btn-default" do %>
    <i class="fa fa-reply"></i> Voltar
<% end %>

app/views/businesses/index.csv.erb
<%- headers = ['Razão Social', 'Apelido', 'Segmento', 'CNPJ', 'Inscrição Estadual', 'Endereço', 'Nº', 'Complemento', 'Bairro', 'Cidade', 'CEP', 'UF', 'País', 'Telefone 1', 'Telefone 2', 'FAX', 'Email', 'Site', 'Criado em', 'Atualizado em'] -%>
<%= CSV.generate_line headers %>
<%- @businesses.each do |business| -%>
  <%= CSV.generate_line([business.corporate_name, business.nickname, business.segment, business.cnpj, business.state_registration, business.address, business.number, business.complement, business.district, business.city, business.cep, business.uf, business.country, business.phone1, business.phone2, business.fax, business.email, business.url, business.created_at, business.updated_at]) %>
<%- end -%>

app/views/businesses/index.html.erb
<h1><i class="fa fa-building-o"></i> Empresas</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Apelido</th>
      <th>Segmento</th>
      <th>Contatos</th>
      <th>Cidade</th>
      <th>UF</th>
      <th>País</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Site</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td> <a href="/businesses/<%= business.id %>"><%= business.id %></a></td>
        <td><%= business.nickname %></td>
        <td><%= business.segment %></td>
        <td>
        <div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    <i class="fa fa-users"></i>
    <span class="caret"></span>
  </button><ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
  <% business.contacts.each do |contact| %>
  <li role="presentation"> 
<a href="/contacts/<%= contact.id %>"><%= contact.name %> </a></li>
<% end %>
</ul>
</div></td>
        <td><%= business.city %></td>
        <td><%= business.uf %></td>
        <td><%= business.country %></td>
        <td><%= business.phone1 %></td>
</td>
        <td><a href="mailto:<%= business.email %>"><%= business.email %></a> </td>
        <td><a href="http://<%= business.url %>" target="blank"><%= business.url %></a> </td>
<td> 
  <div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    <i class="fa fa-cog"></i>
    <span class="caret"></span>
  </button><ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
  <li role="presentation"><!--<i class="fa fa-eye"></i>-->
  <%= link_to 'Ver', business %></li>
  <li role="presentation"><!--<i class="fa fa-pencil-square-o">-->
  </i> <%= link_to 'Editar', edit_business_path(business) %></li>
  <li role="presentation" class="disabled"><!--<i class="fa fa-trash-o">-->
  </i> <%= link_to 'Excluir', business, method: :delete, data: { confirm: 'Você tem certeza?' } %></li>
</ul>
</div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_business_path, class: "btn btn-primary" do %>
    <i class="fa fa-plus"></i> Nova Empresa
<% end %>

app/views/businesses/new.html.erb
<h1>Nova Empresa</h1>

<%= render 'form' %>

<%= link_to businesses_path, class: "btn btn-default" do %>
    <i class="fa fa-reply"></i> Voltar
<% end %>

app/views/businesses/show.html.erb
<h1> Visualizando Empresa</h1>
<div class="row">
   <div class="form-group">
      <div class="col-md-8">
         <label>Razão Social</label>
         <input class="form-control" disabled="" value="<%= @business.corporate_name%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-4">
         <label>Apelido</label>
         <input class="form-control" disabled="" value="<%= @business.nickname%>">
      </div>
      <div class="col-md-4">
         <label>Segmento</label>
         <input class="form-control" disabled="" value="<%= @business.segment%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-4">
         <label>CNPJ</label>
         <input class="form-control" disabled="" value="<%= @business.cnpj%>">
      </div>
      <div class="col-md-4">
         <label>Inscrição Estadual</label>
         <input class="form-control" disabled="" value="<%= @business.state_registration%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-6">
         <label>Endereço</label>
         <input class="form-control" disabled="" value="<%= @business.address%>">
      </div>
      <div class="col-md-2">
         <label>Nº</label>
         <input class="form-control" disabled="" value="<%= @business.number%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-4">
         <label>Bairro</label>
         <input class="form-control" disabled="" value="<%= @business.district%>">
      </div>
      <div class="col-md-4">
         <label>Cidade</label>
         <input class="form-control" disabled="" value="<%= @business.city%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-5">
         <label>Complemeto</label>
         <input class="form-control" disabled="" value="<%= @business.complement%>">
      </div>
      <div class="col-md-2">
         <label>CEP</label>
         <input class="form-control" disabled="" value="<%= @business.cep%>">
      </div>
      <div class="col-md-1">
         <label>UF</label>
         <input class="form-control" disabled="" value="<%= @business.uf%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-3">
         <label>FAX</label>
         <input class="form-control" disabled="" value="<%= @business.fax%>">
      </div>
      <div class="col-md-5">
         <label>País</label>
         <input class="form-control" disabled="" value="<%= @business.country%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-4">
         <label>Telefone 1</label>
         <input class="form-control" disabled="" value="<%= @business.phone1%>">
      </div>
      <div class="col-md-4">
         <label>Telefone 2</label>
         <input class="form-control" disabled="" value="<%= @business.phone2%>">
      </div>
   </div>
</div>
<div class="row">
<div class="form-group">
   <div class="col-md-4">
      <label>Email</label>
      <input class="form-control" disabled="" value="<%= @business.email%>">
   </div>
   <div class="col-md-4">
      <label>Site</label>
      <input class="form-control" disabled="" value="<%= @business.url%>">
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-8">
         <label>Outras informações</label>
         <textarea class="form-control" row="5" disabled="" ><%= @business.other%></textarea>
      </div>
   </div>
</div>
</div>
<br>
<div class="row">
<div class="form-group">
    <div class="col-md-1">
<%= link_to edit_business_path, class: "btn btn-warning" do %>
    <i class="fa fa-pencil-square-o"></i> Editar
<% end %>
</div>
<div class="col-md-1">
<%= link_to businesses_path, class: "btn btn-default" do %>
    <i class="fa fa-reply"></i> Voltar
<% end %>
</div>
</div>
</div>

app/views/contacts/edit.html.erb
<h1>Editando Contato</h1>

<%= render 'form' %>

<%= link_to contacts_path, class: "btn btn-default" do %>
    <i class="fa fa-reply"></i> Voltar
<% end %>

app/views/contacts/index.csv.erb
<%- headers = ['Nome', 'Cargo', 'Telefone', 'Ramal', 'Email', 'Empresa'] -%>
<%= CSV.generate_line headers %>
<%- @contacts.each do |contact| -%>
  <%= CSV.generate_line([contact.name, contact.position, contact.phone, contact.ramal, contact.email, contact.business.nickname]) %>
<%- end -%>

app/views/contacts/index.html.erb
<h1><i class="fa fa-users"></i> Contatos</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Cargo</th>
      <th>Telefone</th>
      <th>Ramal</th>
      <th>Email</th>
      <th>Empresa</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><a href="/contacts/<%= contact.id %>"><%= contact.id %></a></td>
        <td><%= contact.name %></td>
        <td><%= contact.position %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.ramal %></td>
        <td><a href="mailto:<%= contact.email %>"><%= contact.email %></td>
        <td><%= contact.business.nickname %></td>
        <td>        <div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    <i class="fa fa-cog"></i>
    <span class="caret"></span>
  </button><ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
  <li role="presentation"><!--<i class="fa fa-eye"></i>-->
  <%= link_to 'Ver', contact %></li>
  <li role="presentation"><!--<i class="fa fa-pencil-square-o">-->
  </i> <%= link_to 'Editar', edit_contact_path(contact) %></li>
  <li role="presentation" class="disabled"><!--<i class="fa fa-trash-o">-->
  </i> <%= link_to 'Excluir', contact, method: :delete, data: { confirm: 'Você tem certeza?' } %></li>
</ul>
</div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_contact_path, class: "btn btn-primary" do %>
    <i class="fa fa-plus"></i> Novo Contato
<% end %>

app/views/contacts/new.html.erb
<h1>Novo Contato</h1>

<%= render 'form' %>

<%= link_to contacts_path, class: "btn btn-default" do %>
    <i class="fa fa-reply"></i> Voltar
<% end %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
   <div class="form-group">
      <div class="col-md-6">
         <label>Nome</label>
         <input class="form-control" disabled="" value="<%= @contact.name%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-6">
         <label>Cargo</label>
         <input class="form-control" disabled="" value="<%= @contact.position%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-4">
         <label>Telefone</label>
         <input class="form-control" disabled="" value="<%= @contact.phone%>">
      </div>
      <div class="col-md-2">
         <label>Ramal</label>
         <input class="form-control" disabled="" value="<%= @contact.ramal%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-4">
         <label>Email</label>
         <input class="form-control" disabled="" value="<%= @contact.email%>">
      </div>
      <div class="col-md-2">
         <label>Empresa</label>
         <input class="form-control" disabled="" value="<%= @contact.business.nickname%>">
      </div>
   </div>
</div>
<div class="row">
   <div class="form-group">
      <div class="col-md-6">
         <label>Outras informações</label>
         <textarea class="form-control" row="5" disabled="" ><%= @contact.other%></textarea>
      </div>
   </div>
</div>
</div>
<br>
<div class="row">
<div class="form-group">
    <div class="col-md-1">
<%= link_to edit_contact_path, class: "btn btn-warning" do %>
    <i class="fa fa-pencil-square-o"></i> Editar
<% end %>
</div>
<div class="col-md-1">
<%= link_to contacts_path, class: "btn btn-default" do %>
    <i class="fa fa-reply"></i> Voltar
<% end %>
</div>
</div>
</div>

app/views/others/_form.html.erb
<%= form_for(@other) do |f| %>
  <% if @other.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@other.errors.count, "error") %> prohibited this other from being saved:</h2>

      <ul>
      <% @other.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :other, "Outras Informações" %><br>
    <%= f.text_area :other %>
  </div>
  <div class="field">
    <%= f.label :business_id %><br>
    <%= f.number_field :business_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/others/edit.html.erb
<h1>Editing Other</h1>

<%= render 'form' %>

<%= link_to 'Show', @other %> |
<%= link_to 'Back', others_path %>

app/views/others/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Others</h1>

<table>
  <thead>
    <tr>
      <th>Other</th>
      <th>Business</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @others.each do |other| %>
      <tr>
        <td><%= other.other %></td>
        <td><%= other.business_id %></td>
        <td><%= link_to 'Show', other %></td>
        <td><%= link_to 'Edit', edit_other_path(other) %></td>
        <td><%= link_to 'Destroy', other, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Other', new_other_path %>

app/views/others/new.html.erb
<h1>New Other</h1>

<%= render 'form' %>

<%= link_to 'Back', others_path %>

app/views/others/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Other:</strong>
  <%= @other.other %>
</p>

<p>
  <strong>Business:</strong>
  <%= @other.business_id %>
</p>

<%= link_to 'Edit', edit_other_path(@other) %> |
<%= link_to 'Back', others_path %>

app/views/shared/_navigation.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                <%=image_tag('logo.png')%>
                </a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right ">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-building-o fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="/businesses/new/"><i class="fa fa-file-o"></i> Nova Empresa </a>
                        </li>
                        <li><a href="/businesses/"><i class="fa fa-list-ul"></i> Ver Todas </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-users fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="/contacts/new"><i class="fa fa-file-o"></i> Novo Contato </a>
                        </li>
                        <li><a href="/contacts/"><i class="fa fa-list-ul"></i> Ver Todos </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-database fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                                    <%= link_to businesses_path(format: :csv) do %>
    <i class="fa fa-download"></i> Empresas</li>
<% end %>     
                                </li>
                                <li>
                                    <%= link_to contacts_path(format: :csv) do %>
    <i class="fa fa-download"></i> Contatos</li>
    <% end %> 
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar " role="navigation">
                <div class="sidebar-nav navbar-collapse collapse">
                    <ul class="nav" id="side-menu">
                          <%= form_tag(businesses_path, :method => "get", id: "search-form") do %>
  
                                 <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <%= text_field_tag :search, params[:search], placeholder: "", class: "form-control"  %>
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                                <% end %>
                            </span>
                            </div>
                            
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="/"><i class="fa fa-dashboard fa-fw"></i> Painel Central</a>
                        </li>
                        <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#business"><i class="fa fa-building-o fa-fw"></i> Empresas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse" id="business">
                                <li>
                                    <a href="/businesses/new"><i class="fa fa-file-o"></i> Adicionar Nova</a>
                                </li>
                                <li>
                                    <a href="/businesses/"><i class="fa fa-list-ul"></i> Ver Todas</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                             <a href="javascript:;" data-toggle="collapse" data-target="#contact"><i class="fa fa-users fa-fw"></i> Contatos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse" id="contact">
                                <li>
                                    <a href="/contacts/new"><i class="fa fa-file-o"></i> Adicionar Novo</a>
                                </li>
                                <li>
                                    <a href="/contacts/"><i class="fa fa-list-ul"></i> Ver Todos</a>
                                </li>
                    </ul>
                        <li>
                             <a href="javascript:;" data-toggle="collapse" data-target="#download"><i class="fa fa-database fa-fw"></i> Exportar<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse" id="download">
                                <li>
                                    <%= link_to businesses_path(format: :csv) do %>
    <i class="fa fa-download"></i> Empresas</li>
<% end %>     
                                </li>
                                <li>
                                    <%= link_to contacts_path(format: :csv) do %>
    <i class="fa fa-download"></i> Contatos</li>
<% end %>     
                    </ul>               
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>